### PR TITLE
Possible fix for #151 issue

### PR DESCRIPTION
**Pull request by stondo**
code added to make it work with elastic 2 and mongo (now it's possible to use _id)

### CODE REVIEW

**Comment by sunshineo** [comment]
Thank you @stondo for the merge request but don't merge it!
This is not a proper fix. This will make elastic search randomly generate an id. If transporter ran twice, you got twice the documents.
What we need is not simply delete the id but move it onto the url for elastic search 2.0+

**Comment by stondo** [comment]
@sunshineo that's not right. We just verified that what u describe won't happen.
It's because the elasticgo driver gets the id as parameter and already makes the instertion with the id. 
See the code code snippet below, taken from pkg/adaptor/elasticsearch.go:

    default:
    		err = e.indexer.Index(e.index, _type, id, "", "", nil, msg.Data, false)
    }

**Comment by sunshineo** [comment]
@stondo  I'm very surprised if that is the case. Because I experienced the duplication right after I used transform js files to remove _id from the document. And I had to downgrade elastic search.
When you test, did you use any transform js files?

**Comment by stondo** [comment]
well, we r pretty sure, we don't have any dupes. Imported around 7milion records and ran lot's of queries against those data. We r running a very simple transformation:

    module.exports = function(doc) {
      delete doc.data.connectedIds;
      delete doc.data.connectingIds;
      return doc;
    }

which hasn't got anything to do with _id.

Our goal was to have mongo _id and elastic2 _id being the same.

**Comment by sunshineo** [comment]
OK. I'll try sometime later.

**Comment by robpc** [comment]
I would like to weight in that I have also been playing around with this pull request and found that it did not create duplicates (testing only but with production data).

**Comment by jipperinbham** [comment]
closing in favor of #233

**Pull request closed without merging**
