### PR TITLE
Twitter: Second pass at getting Twitter adaptor in

### PR DESCRIPTION
**Pull request by codepope**
Twitter adaptor with enhanced error handling over original and better
ability to stay running.

Configure with credentials from Twitter in config.yaml

Keyword parameter will "sample" public feed if left empty, otherwise
return Twitter tracking feeds for the comma-separated words.

### CODE REVIEW

**Comment by jipperinbham** [comment]
I don't feel like the main project is the place for this adaptor. Is there a reason you chose not to update the one [here](https://github.com/compose/transporter-examples/tree/master/go/cmd/twitter)?

**Comment by codepope** [comment]
Because that example makes a stand alone command while
The Twitter adaptor is more robust and built so you can work with a flow of relatively rich JSON documents in theTransformer. It also lets you subject a cb to a steady stream of inserts or keyword selected tweets.

**Comment by nstott** [comment]
I agree with jp, I think this makes a good example, but I don't think it belongs in the core set of adaptors

**Comment by jipperinbham** [comment]
closing this for now

a future version of transporter will hopefully be able to support external adaptors with the new `plugin` package in Go 1.8

**Pull request closed without merging**
