### PR TITLE
Add kinesis adaptor

### PR DESCRIPTION
**Pull request by rishiloyola**
Kinesis adaptor is capable of fetch and pushing live data from AWS Kinesis stream to transporter's pipeline. It’s able to operate in live tail mode and includes proper handling.

Configure your credentials for AWS Kinesis in the config.yaml file.

There is also a sample setup in test/application-kinesis-file.js which writes the stream output to a file. The application is responsible for building transporter pipelines.

Commands to test and run it locally **:**

```
transporter test --config test/config.yaml test/application-kinesis-file.js
transporter run --config test/config.yaml test/application-kinesis-file.js
```

**Note :** It has one external dependency, the **go-kinesis** lib from Sendgrid, it provides better accessibility and abstraction than AWS’s official Go SDK.

### CODE REVIEW

**Comment by trinchan** [comment]
thank you for your contribution. we love having community interest in the project! as for 3rd party adaptors, we are hesitant to bring them into the main project because at the moment we don't have a good way of maintaining the adaptors due to things like API changes. we are considering a few solutions on how to easily bring in community adaptors in a way that is also maintainable. check back soon and thanks again for your work!

**Comment by siddharthlatest** [comment]
@trinchan I see recent activity on the experimental branch. Are you thinking of stabilizing the adaptor APIs before merging new adaptors into the project? Is there a ETA / roadmap on when we will get there?

Personally, I would like to see a source adaptor like kinesis / kafka with transporter. They are used in a lot of ETL pipelines and make for good live-tailing use-cases too.

**Comment by rishiloyola** [comment]
@trinchan bump 😄 
Saw your recent work on etcd adaptor. If my adaptor fits the interface, do you think we can merge this in experimental?

**Comment by jipperinbham** [comment]
@rishiloyola if you are still up for it, can you redo a PR against the `experimental` branch? It's getting close to being merged into master.

**Comment by rishiloyola** [comment]
@jipperinbham I pushed my code into the new [pr](https://github.com/compose/transporter/pull/215). Which is against `experimental ` branch. You can close this pr.

**Comment by jipperinbham** [comment]
thanks! closing in favor of https://github.com/compose/transporter/pull/215

**Pull request closed without merging**
