### PR TITLE
FIX: delete `_id` key to allow elastic insertions

### PR DESCRIPTION
**Pull request by ndouba**
This addresses issues https://github.com/compose/transporter/issues/165 and https://github.com/compose/transporter/issues/167.

### CODE REVIEW

**Comment by gustavodegeus** [comment]
+1

**Comment by mccraveiro** [comment]
What if I actually want to set a id?

**Comment by allfro** [comment]
@mccraveiro this patch addresses this concern. The elastic API ignores setting an identifier through the document body using `_id`. It will silently create a new identifier and overwrite yours. This patch simply deletes the `_id` from the message body since it is already being passed in as an argument to the elastic index in a later call. So that same identifier is used without being dropped/ignored.

**Comment by jipperinbham** [comment]
closing in favor of #233

**Pull request closed without merging**
