### PR TITLE
Update READMEWINDOWS.md

### PR DESCRIPTION
**Pull request by juliogt89**
http://mercurial.selenic.com/wiki/Download : Broken Link / ERR_NAME_NOT_RESOLVED

### Required for all PRs:

- [ ] CHANGELOG.md updated (feel free to wait until changes have been reviewed by a maintainer)
- [ ] README.md updated (if needed)

### CODE REVIEW

**Comment by codepope** [comment]
An alternative download isn't really needed. Selenic just updated their site so the new URL is  just https://www.mercurial-scm.org/downloads - the current version is 4.2.1 and unless the builder has a very old Python, this is probably best. More importantly, with recent Go's should have eliminated the need for mercurial in this process.

**Comment by jipperinbham** [comment]
what's the right approach here? Is mercurial still required for using Go on windows?

**Comment by codepope** [comment]
I don't believe so, but I'll look at bringing up a Windows box and create new Windows instructions based on that.

**Comment by jipperinbham** [comment]
ping @codepope :)

**Comment by jipperinbham** [comment]
closing in favor of #384

**Pull request closed without merging**
