### PR TITLE
Issue 391 increase write timeouts

### PR DESCRIPTION
**Pull request by johnjjung**
### Required for all PRs:

- [ ] CHANGELOG.md updated (feel free to wait until changes have been reviewed by a maintainer)
- [ ] README.md updated (if needed)

### CODE REVIEW

**Comment by johnjjung** [comment]
Resolving issue https://github.com/compose/transporter/issues/391

Tested by increasing write timeouts.
Asking for Suggestions for how to implement this, `defaultWriteTimeout` is currently a const.

So only changing this at adapter client level doesn't seem to prevent this error.

**Comment by jipperinbham** [comment]
sorry I didn't get a chance to reply back in #391, the write timeout is configurable in the pipeline.js by doing the following:

```javascript
t.Config({"write_timeout":"30s"}).Source("source", source).Save("sink", sink)
```

If you'd like to convert this PR to document this, that'd be great!

**Comment by johnjjung** [comment]
Perfect, will update documentation and reverse commit

**Comment by kanukanukanu** [comment]
@jipperinbham 
i added this code in pipeline.js
`t.Config({"write_timeout":"30s"}).Source("source", source).Save("sink", sink)`

but "context deadline exceeded" continuously appeared.
It have made me so tough...

**Comment by johnjjung** [comment]
@kanukanukanu can you turn logs on and see where it’s going wrong? It might not be a timeout errror on transporter side

**Comment by kanukanukanu** [comment]
Thanks John.

I have solved that issue.
t.Config setting is adequate.

But can I ask you one more question?
When I transfer mongoDB to EalsticSearch, can I send data rapidly?

Sam

**Pull request closed without merging**
